import './globals.css';

export const metadata = {
  title: 'PT QUICKNET NUSANTARA TEKNOLOGI',
  description: 'Generated by create next app',
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/icon.png"></link>
      <body>{children}</body>
    </html>
  );
}
