// pages/about.js

import '../app/globals.css';
import Navbar from '../components/Navbar/Navbar';
import Footer from '../components/Footer/Footer';
import React from 'react';
import AboutHero from '@/components/AboutHero/AboutHero';
import MissionVision from '@/components/MissionVision/MissionVision';
import StatsSection from '@/components/StatsSection/StatsSection';

export const metadata = {
  title: 'About Us - PT QUICKNET NUSANTARA TEKNOLOGI',
  description: 'Generated by create next app',
};

export default function About() {
  return (
    <div>
      <title>About Us - PT QUICKNET NUSANTARA TEKNOLOGI</title>
      <Navbar />

      <main>
        {/* 1. Judul dan Sejarah Singkat */}
        <AboutHero />

        {/* 2. Visi, Misi, dan Nilai Inti */}
        <MissionVision />

        {/* 3. Kredibilitas dalam Angka (Reusable) */}
        <StatsSection />

        {/* 4. Profil Tim (Opsional) */}
        {/* <TeamSection /> */}
      </main>

      <Footer />
    </div>
  );
}
